# Core GraphQL Type Definitions
scalar DateTime


""" Telemetry payload node 21293 """
type 24224 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7308 """
type 9391 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 32391 """
type 32472 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 15873 """
type 24171 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 27822 """
type 8528 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 8772 """
type 12108 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 12681 """
type 31536 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 20146 """
type 31561 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 1382 """
type 23053 {
  id: ID!
  status: String!
  updatedAt: DateTime
}
