# Core GraphQL Type Definitions
scalar DateTime


""" Telemetry payload node 21293 """
type 24224 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7308 """
type 9391 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 32391 """
type 32472 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 15873 """
type 24171 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 27822 """
type 8528 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 8772 """
type 12108 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 12681 """
type 31536 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 20146 """
type 31561 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 1382 """
type 23053 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 22072 """
type 29095 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 10039 """
type 4150 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 15445 """
type 9003 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 6364 """
type 25107 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 21534 """
type 16492 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 2094 """
type 1179 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 21170 """
type 26216 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 288 """
type 4612 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 23311 """
type 27935 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 30792 """
type 31122 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7838 """
type 23557 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 9772 """
type 14530 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 4921 """
type 24179 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 8894 """
type 15055 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 17088 """
type 24202 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 26642 """
type 20649 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 15427 """
type 20 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 21978 """
type 32578 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 4545 """
type 2693 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 32486 """
type 6886 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 14578 """
type 21867 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 25824 """
type 21379 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 9909 """
type 4959 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 13275 """
type 17084 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 12240 """
type 27562 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 15891 """
type 22826 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 10764 """
type 19372 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 27827 """
type 29495 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 11085 """
type 7360 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 14521 """
type 31003 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 22738 """
type 18532 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 20463 """
type 15448 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 1843 """
type 16110 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 5241 """
type 19161 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 13249 """
type 18747 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 26792 """
type 27999 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 28849 """
type 10158 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7167 """
type 3920 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 17482 """
type 26631 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 17464 """
type 31000 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 4838 """
type 27883 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 13897 """
type 4265 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 21553 """
type 23096 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 6364 """
type 5803 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 1317 """
type 19438 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 21845 """
type 12096 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 19267 """
type 25719 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 9276 """
type 4457 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 31825 """
type 1223 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 13358 """
type 20117 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 18718 """
type 7863 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 8146 """
type 2360 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 13333 """
type 31042 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 18044 """
type 13227 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7560 """
type 6479 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 21209 """
type 11286 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 17009 """
type 31055 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 20715 """
type 28318 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 26443 """
type 14354 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 10003 """
type 31451 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 17563 """
type 5619 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 16784 """
type 16070 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7740 """
type 8779 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 5076 """
type 361 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 29028 """
type 2087 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 28779 """
type 4051 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 2223 """
type 17863 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 26763 """
type 5493 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 15698 """
type 1176 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 14474 """
type 642 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 23596 """
type 8885 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 13327 """
type 7439 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 11292 """
type 19970 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 32623 """
type 6585 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 3537 """
type 6040 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 28619 """
type 29076 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 23610 """
type 18724 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 6010 """
type 30140 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 3683 """
type 26807 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 7656 """
type 3703 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 30761 """
type 15770 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 5777 """
type 4307 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 9589 """
type 3986 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 9118 """
type 11649 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 25433 """
type 17747 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 3165 """
type 20761 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 14366 """
type 22055 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 6916 """
type 1869 {
  id: ID!
  status: String!
  updatedAt: DateTime
}

""" Telemetry payload node 28132 """
type 10921 {
  id: ID!
  status: String!
  updatedAt: DateTime
}
